export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST'
export const GET_COMPANY_SUCCESS = 'GET_USER_SUCCESS'
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE'

export const GET_COMPANIES_LIST_REQUEST = 'GET_COMPANIES_LIST_REQUEST'
export const GET_COMPANIES_LIST_SUCCESS = 'GET_COMPANIES_LIST_SUCCESS'
export const GET_COMPANIES_LIST_FAILURE = 'GET_COMPANIES_LIST_FAILURE'

