import { css } from '@emotion/css';
import { makeStyles, styled } from '@mui/material/styles';



const converted = {
  ".bg-primary": { backgroundColor: "#13618d !important" },
  ".text-primary": { color: "#13618d !important" },
  ".bg-secondary": { backgroundColor: "#d3d3d3 !important" },
  ".text-secondary": { color: "#d3d3d3 !important" },
  ".bg-success": { backgroundColor: "#149f50 !important" },
  ".text-success": { color: "#149f50 !important" },
  ".bg-info": { backgroundColor: "#eee !important" },
  ".text-info": { color: "#eee !important" },
  ".bg-warning": { backgroundColor: "#ffa441 !important" },
  ".text-warning": { color: "#ffa441 !important" },
  ".bg-danger": { backgroundColor: "#ee1e32 !important" },
  ".text-danger": { color: "#ee1e32 !important" },
  ".bg-light": { backgroundColor: "#eee !important" },
  ".text-light": { color: "#eee !important" },
  ".bg-dark": { backgroundColor: "#eee !important" },
  ".text-dark": { color: "#eee !important" },
  ".bg-white": { backgroundColor: "#fff !important" },
  ".text-white": { color: "#fff !important" },
  ".bg-black": { backgroundColor: "#000 !important" },
  ".text-black": { color: "#000 !important" },
  ".m-0": { margin: "0mm" },
  ".ms-0": { marginLeft: "0mm" },
  ".mt-0": { marginTop: "0mm" },
  ".me-0": { marginRight: "0mm" },
  ".mb-0": { marginBottom: "0mm" },
  ".mx-0": { marginLeft: "0mm !important", marginRight: "0mm !important" },
  ".my-0": { marginTop: "0mm !important", marginBottom: "0mm !important" },
  ".p-0": { padding: "0mm" },
  ".ps-0": { paddingLeft: "0mm" },
  ".pt-0": { paddingTop: "0mm" },
  ".pe-0": { paddingRight: "0mm" },
  ".pb-0": { paddingBottom: "0mm" },
  ".px-0": { paddingLeft: "0mm !important", paddingRight: "0mm !important" },
  ".py-0": { paddingTop: "0mm !important", paddingBottom: "0mm !important" },
  ".round-0": { borderRadius: "0mm" },
  ".b-0": { border: "0mm solid #000" },
  ".m-1": { margin: "0.5mm" },
  ".ms-1": { marginLeft: "0.5mm" },
  ".mt-1": { marginTop: "0.5mm" },
  ".me-1": { marginRight: "0.5mm" },
  ".mb-1": { marginBottom: "0.5mm" },
  ".mx-1": { marginLeft: "0.5mm !important", marginRight: "0.5mm !important" },
  ".my-1": { marginTop: "0.5mm !important", marginBottom: "0.5mm !important" },
  ".p-1": { padding: "0.5mm" },
  ".ps-1": { paddingLeft: "0.5mm" },
  ".pt-1": { paddingTop: "0.5mm" },
  ".pe-1": { paddingRight: "0.5mm" },
  ".pb-1": { paddingBottom: "0.5mm" },
  ".px-1": {
    paddingLeft: "0.5mm !important",
    paddingRight: "0.5mm !important"
  },
  ".py-1": {
    paddingTop: "0.5mm !important",
    paddingBottom: "0.5mm !important"
  },
  ".round-1": { borderRadius: "0.5mm" },
  ".b-1": { border: "0.375mm solid #000" },
  ".m-2": { margin: "1mm" },
  ".ms-2": { marginLeft: "1mm" },
  ".mt-2": { marginTop: "1mm" },
  ".me-2": { marginRight: "1mm" },
  ".mb-2": { marginBottom: "1mm" },
  ".mx-2": { marginLeft: "1mm !important", marginRight: "1mm !important" },
  ".my-2": { marginTop: "1mm !important", marginBottom: "1mm !important" },
  ".p-2": { padding: "1mm" },
  ".ps-2": { paddingLeft: "1mm" },
  ".pt-2": { paddingTop: "1mm" },
  ".pe-2": { paddingRight: "1mm" },
  ".pb-2": { paddingBottom: "1mm" },
  ".px-2": { paddingLeft: "1mm !important", paddingRight: "1mm !important" },
  ".py-2": { paddingTop: "1mm !important", paddingBottom: "1mm !important" },
  ".round-2": { borderRadius: "1mm" },
  ".b-2": { border: "0.75mm solid #000" },
  ".m-3": { margin: "1.5mm" },
  ".ms-3": { marginLeft: "1.5mm" },
  ".mt-3": { marginTop: "1.5mm" },
  ".me-3": { marginRight: "1.5mm" },
  ".mb-3": { marginBottom: "1.5mm" },
  ".mx-3": { marginLeft: "1.5mm !important", marginRight: "1.5mm !important" },
  ".my-3": { marginTop: "1.5mm !important", marginBottom: "1.5mm !important" },
  ".p-3": { padding: "1.5mm" },
  ".ps-3": { paddingLeft: "1.5mm" },
  ".pt-3": { paddingTop: "1.5mm" },
  ".pe-3": { paddingRight: "1.5mm" },
  ".pb-3": { paddingBottom: "1.5mm" },
  ".px-3": {
    paddingLeft: "1.5mm !important",
    paddingRight: "1.5mm !important"
  },
  ".py-3": {
    paddingTop: "1.5mm !important",
    paddingBottom: "1.5mm !important"
  },
  ".round-3": { borderRadius: "1.5mm" },
  ".b-3": { border: "1.125mm solid #000" },
  ".m-4": { margin: "2mm" },
  ".ms-4": { marginLeft: "2mm" },
  ".mt-4": { marginTop: "2mm" },
  ".me-4": { marginRight: "2mm" },
  ".mb-4": { marginBottom: "2mm" },
  ".mx-4": { marginLeft: "2mm !important", marginRight: "2mm !important" },
  ".my-4": { marginTop: "2mm !important", marginBottom: "2mm !important" },
  ".p-4": { padding: "2mm" },
  ".ps-4": { paddingLeft: "2mm" },
  ".pt-4": { paddingTop: "2mm" },
  ".pe-4": { paddingRight: "2mm" },
  ".pb-4": { paddingBottom: "2mm" },
  ".px-4": { paddingLeft: "2mm !important", paddingRight: "2mm !important" },
  ".py-4": { paddingTop: "2mm !important", paddingBottom: "2mm !important" },
  ".round-4": { borderRadius: "2mm" },
  ".b-4": { border: "1.5mm solid #000" },
  ".m-5": { margin: "2.5mm" },
  ".ms-5": { marginLeft: "2.5mm" },
  ".mt-5": { marginTop: "2.5mm" },
  ".me-5": { marginRight: "2.5mm" },
  ".mb-5": { marginBottom: "2.5mm" },
  ".mx-5": { marginLeft: "2.5mm !important", marginRight: "2.5mm !important" },
  ".my-5": { marginTop: "2.5mm !important", marginBottom: "2.5mm !important" },
  ".p-5": { padding: "2.5mm" },
  ".ps-5": { paddingLeft: "2.5mm" },
  ".pt-5": { paddingTop: "2.5mm" },
  ".pe-5": { paddingRight: "2.5mm" },
  ".pb-5": { paddingBottom: "2.5mm" },
  ".px-5": {
    paddingLeft: "2.5mm !important",
    paddingRight: "2.5mm !important"
  },
  ".py-5": {
    paddingTop: "2.5mm !important",
    paddingBottom: "2.5mm !important"
  },
  ".round-5": { borderRadius: "2.5mm" },
  ".b-5": { border: "1.875mm solid #000" },
  ".m-6": { margin: "3mm" },
  ".ms-6": { marginLeft: "3mm" },
  ".mt-6": { marginTop: "3mm" },
  ".me-6": { marginRight: "3mm" },
  ".mb-6": { marginBottom: "3mm" },
  ".mx-6": { marginLeft: "3mm !important", marginRight: "3mm !important" },
  ".my-6": { marginTop: "3mm !important", marginBottom: "3mm !important" },
  ".p-6": { padding: "3mm" },
  ".ps-6": { paddingLeft: "3mm" },
  ".pt-6": { paddingTop: "3mm" },
  ".pe-6": { paddingRight: "3mm" },
  ".pb-6": { paddingBottom: "3mm" },
  ".px-6": { paddingLeft: "3mm !important", paddingRight: "3mm !important" },
  ".py-6": { paddingTop: "3mm !important", paddingBottom: "3mm !important" },
  ".round-6": { borderRadius: "3mm" },
  ".b-6": { border: "2.25mm solid #000" },
  ".m-7": { margin: "3.5mm" },
  ".ms-7": { marginLeft: "3.5mm" },
  ".mt-7": { marginTop: "3.5mm" },
  ".me-7": { marginRight: "3.5mm" },
  ".mb-7": { marginBottom: "3.5mm" },
  ".mx-7": { marginLeft: "3.5mm !important", marginRight: "3.5mm !important" },
  ".my-7": { marginTop: "3.5mm !important", marginBottom: "3.5mm !important" },
  ".p-7": { padding: "3.5mm" },
  ".ps-7": { paddingLeft: "3.5mm" },
  ".pt-7": { paddingTop: "3.5mm" },
  ".pe-7": { paddingRight: "3.5mm" },
  ".pb-7": { paddingBottom: "3.5mm" },
  ".px-7": {
    paddingLeft: "3.5mm !important",
    paddingRight: "3.5mm !important"
  },
  ".py-7": {
    paddingTop: "3.5mm !important",
    paddingBottom: "3.5mm !important"
  },
  ".round-7": { borderRadius: "3.5mm" },
  ".b-7": { border: "2.625mm solid #000" },
  ".m-8": { margin: "4mm" },
  ".ms-8": { marginLeft: "4mm" },
  ".mt-8": { marginTop: "4mm" },
  ".me-8": { marginRight: "4mm" },
  ".mb-8": { marginBottom: "4mm" },
  ".mx-8": { marginLeft: "4mm !important", marginRight: "4mm !important" },
  ".my-8": { marginTop: "4mm !important", marginBottom: "4mm !important" },
  ".p-8": { padding: "4mm" },
  ".ps-8": { paddingLeft: "4mm" },
  ".pt-8": { paddingTop: "4mm" },
  ".pe-8": { paddingRight: "4mm" },
  ".pb-8": { paddingBottom: "4mm" },
  ".px-8": { paddingLeft: "4mm !important", paddingRight: "4mm !important" },
  ".py-8": { paddingTop: "4mm !important", paddingBottom: "4mm !important" },
  ".round-8": { borderRadius: "4mm" },
  ".b-8": { border: "3mm solid #000" },
  ".m-9": { margin: "4.5mm" },
  ".ms-9": { marginLeft: "4.5mm" },
  ".mt-9": { marginTop: "4.5mm" },
  ".me-9": { marginRight: "4.5mm" },
  ".mb-9": { marginBottom: "4.5mm" },
  ".mx-9": { marginLeft: "4.5mm !important", marginRight: "4.5mm !important" },
  ".my-9": { marginTop: "4.5mm !important", marginBottom: "4.5mm !important" },
  ".p-9": { padding: "4.5mm" },
  ".ps-9": { paddingLeft: "4.5mm" },
  ".pt-9": { paddingTop: "4.5mm" },
  ".pe-9": { paddingRight: "4.5mm" },
  ".pb-9": { paddingBottom: "4.5mm" },
  ".px-9": {
    paddingLeft: "4.5mm !important",
    paddingRight: "4.5mm !important"
  },
  ".py-9": {
    paddingTop: "4.5mm !important",
    paddingBottom: "4.5mm !important"
  },
  ".round-9": { borderRadius: "4.5mm" },
  ".b-9": { border: "3.375mm solid #000" },
  ".m-10": { margin: "5mm" },
  ".ms-10": { marginLeft: "5mm" },
  ".mt-10": { marginTop: "5mm" },
  ".me-10": { marginRight: "5mm" },
  ".mb-10": { marginBottom: "5mm" },
  ".mx-10": { marginLeft: "5mm !important", marginRight: "5mm !important" },
  ".my-10": { marginTop: "5mm !important", marginBottom: "5mm !important" },
  ".p-10": { padding: "5mm" },
  ".ps-10": { paddingLeft: "5mm" },
  ".pt-10": { paddingTop: "5mm" },
  ".pe-10": { paddingRight: "5mm" },
  ".pb-10": { paddingBottom: "5mm" },
  ".px-10": { paddingLeft: "5mm !important", paddingRight: "5mm !important" },
  ".py-10": { paddingTop: "5mm !important", paddingBottom: "5mm !important" },
  ".round-10": { borderRadius: "5mm" },
  ".b-10": { border: "3.75mm solid #000" },
  ".col-1": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-2": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-3": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-4": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-5": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-6": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-7": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-8": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-9": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-10": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-11": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".col-12": { flex: "0 0 auto", width: "calc(($i * 100%) / 12)" },
  ".fw-100": { fontWeight: 100 },
  ".fw-300": { fontWeight: 300 },
  ".fw-400": { fontWeight: 400 },
  ".fw-500": { fontWeight: 500 },
  ".fw-700": { fontWeight: 700 },
  ".fw-900": { fontWeight: 900 },
  "*": {
    margin: "0",
    padding: "0",
    boxSizing: "border-box",
    colorAdjust: "exact !important",
    WebkitPrintColorAdjust: "exact !important",
    printColorAdjust: "exact !important"
  },
  body: { fontSize: "0.64rem", fontFamily: '"Roboto", sans-serif' },
  ".page": {
    width: "21cm",
    minHeight: "29.7cm",
    maxHeight: "29.7cm",
    padding: "1cm",
    margin: "0 auto",
    border: "1px #d3d3d3 solid",
    borderRadius: "5px",
    background: "white",
    boxShadow: "0 0 5px rgba(0, 0, 0, 0.1)"
  },
  ".d-flex": { display: "flex" },
  ".flex-col": { flexDirection: "column" },
  ".d-block": { display: "block" },
  ".align-items-center": { alignItems: "center" },
  ".align-self-start": { alignSelf: "start" },
  ".align-items-start": { alignItems: "start !important" },
  ".justify-content-center": { justifyContent: "center" },
  ".justify-content-between": { justifyContent: "space-between" },
  ".text-center": { textAlign: "center" },
  ".text-start": { textAlign: "left" },
  ".text-end": { textAlign: "right" },
  ".text-justify": { textAlign: "justify" },
  ".ls-05": { letterSpacing: "-0.28px" },
  ".ls-1": { letterSpacing: "-0.75px" },
  ".lh-100": { lineHeight: "100%" },
  ".lh-150": { lineHeight: "150%" },
  ".small": { fontSize: "0.5rem" },
  ".smallest": { fontSize: "0.48rem" },
  ".row": { display: "flex", alignItems: "center" },
  ".col": { flex: "1 0 0%" },
  ".col-auto": { flex: "0 0 auto", width: "auto" },
  ".col-35": { maxWidth: "35mm", height: "9mm" },
  ".col-40": { maxWidth: "40mm", minWidth: "40mm", height: "9mm" },
  ".h-7": { minHeight: "7mm" },
  ".border-1": { border: "thin solid #000" },
  ".vh-100": {
    height: "inherit",
    minHeight: "100%",
    border: "thin solid red",
    display: "flex",
    flexDirection: "column",
    flex: 1
  },
  ".form-slot": {
    minHeight: "7mm",
    border: "thin solid black",
    borderRadius: "1mm"
  },
  ".form-slot label": {
    fontSize: "9px",
    fontWeight: 500,
    letterSpacing: "-0.35px",
    marginLeft: "0.5mm"
  },
  ".form-slot.placa": { minHeight: "9mm" },
  ".border-wrapper": {
    border: "thin solid black",
    borderRadius: "1mm",
    height: "100%"
  },
  "header > .row img": { width: "34mm" },
  ".red-tag": {
    maxHeight: "19mm",
    minHeight: "19mm",
    backgroundColor: "#ee1e32",
    padding: "2mm 0mm 2mm 2mm",
    fontSize: "11.5px",
    lineHeight: "140%",
    borderRadius: "1mm"
  },
  ".red-tag > div:first-child": { letterSpacing: "-0.5px" },
  ".blue-slots div": {
    borderRadius: "0.6mm",
    backgroundColor: "#13618d",
    marginTop: "0.3mm",
    padding: "1mm",
    color: "#fff",
    lineHeight: "96%",
    minHeight: "6.8mm",
    maxHeight: "6.8mm",
    display: "flex",
    alignItems: "center",
    letterSpacing: "-0.5px"
  },
  ".blue-slots div.bg-secondary": { justifyContent: "center" },
  ".blue-slots div .form-slot": {
    width: "100% !important",
    backgroundColor: "white",
    maxHeight: "5.4mm",
    height: "5.4mm",
    minHeight: "3.4mm",
    border: "none",
    marginBottom: "1px"
  },
  ".icon-header": {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#13618d",
    color: "white",
    minHeight: "4mm",
    borderRadius: "0.6mm"
  },
  ".icon-header span": {
    width: "100%",
    display: "block",
    padding: "1mm",
    borderRadius: "inherit"
  },
  ".icon-header .icon": {
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    marginLeft: "auto",
    padding: "1mm",
    minHeight: "inherit",
    borderRadius: "inherit"
  },
  ".row.three-checkboxes, .row.two-checkboxes": {
    justifyContent: "space-around",
    minHeight: "6mm",
    maxHeight: "6mm",
    padding: "0.45mm 0"
  },
  ".row.three-checkboxes div, .row.two-checkboxes div": {
    border: "0.5mm solid #000",
    minHeight: "3mm",
    minWidth: "3mm",
    borderRadius: "0.6mm"
  },
  ".row.three-checkboxes div.checked, .row.two-checkboxes div.checked": {
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center"
  },
  ".row.three-checkboxes div.checked:after, .row.three-checkboxes div.checked:before, .row.two-checkboxes div.checked:after, .row.two-checkboxes div.checked:before": {
    content: '""',
    backgroundColor: "#000",
    position: "absolute",
    width: "0.5mm",
    height: "150%",
    transform: "rotateZ(-45deg)"
  },
  ".row.three-checkboxes div.checked:after, .row.two-checkboxes div.checked:after": {
    transform: "rotateZ(45deg)"
  },
  ".row.les-tres": { height: "87mm" },
  ".row.les-tres .col": {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    minHeight: "100%"
  },
  ".row.three-checkboxes": {
    fontSize: "0.5rem",
    letterSpacing: "-0.5px",
    minHeight: "5.4mm",
    maxHeight: "5.4mm"
  },
  ".row .col > div.form-slot:last-child": {
    height: "6.8mm",
    minHeight: "6.8mm"
  },
  hr: { border: "none", borderBottom: "thin solid #aaa" },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "0.44rem",
    height: "1px"
  },
  "table.checks": { fontSize: "0.5rem" },
  "table.checks tr td": { verticalAlign: "middle" },
  "table.checks tr td:last-child": { padding: "0.6mm 0.8mm" },
  "table.checks tr:not(:last-child) td": { borderBottom: "0.01mm solid #eee" },
  "table.checks.last-checks td": { padding: "0.4mm 0.8mm" },
  "table.checks.last-checks td[rowspan]": { border: "none" },
  "table.checks.last-checks td:last-child": { padding: "0" },
  "table tr": { height: "100%" },
  "table td": { height: "100%" },
  "table td > div": { height: "100%" },
  "table.bordered td,\ntable.bordered th": {
    border: "thin solid #000",
    padding: "1px 2px"
  },
  "table.table-head th": { backgroundColor: "#ddd" },
  "table.cell-h-sm th,\ntable.cell-h-sm td": { height: "4.3mm" },
  ".square-check": {
    display: "inline-flex",
    height: "inherit",
    minHeight: "3mm",
    padding: "2px",
    alignItems: "center"
  },
  ".square-check div": {
    width: "2.3mm",
    height: "2.3mm",
    borderRadius: "0.4mm",
    backgroundColor: "#fff"
  },
  ".square-check div.checked": {
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center"
  },
  ".square-check div.checked:after, .square-check div.checked:before": {
    content: '""',
    backgroundColor: "#000",
    position: "absolute",
    width: "0.5mm",
    height: "150%",
    transform: "rotateZ(-45deg)"
  },
  ".square-check div.checked:after": { transform: "rotateZ(45deg)" },
  ".tripe-square-check": { height: "inherit", display: "inline-flex" },
  "figure img": { maxWidth: "100%" },
  ".equal-form-slots .form-slot": { padding: "0.5mm", marginBottom: "0.5mm" },
  ".equal-form-slots.h-12mm .form-slot": { minHeight: "12mm" }
}



const style = makeStyles({
  page: {
    fontSize: "0.64rem",
    width: "21cm",
    minHeight: "29.7cm",
    maxHeight:" 29.7cm",
    padding: "1cm",
    margin:"0 auto",
    border: "1px #d3d3d3 solid",
    borderRadius: "5px",
    background: "white",
    boxShadow: "0 0 5px rgba(0, 0, 0, 0.1)",

    "-webkit-print-color-adjust": "exact !important",
    printColorAdjust: "exact !important",
    boxSizing: "border-box",
    colorAdjust: "exact !important",
    "&header > .row img": { width: "34mm" }
  },
  ".d-flex": { display: "flex" },
  ".flex-col": { flexDirection: "column" },
  ".d-block": { display: "block" },
  ".align-items-center": { alignItems: "center" },
  ".align-self-start": { alignSelf: "start" },
  ".align-items-start": { alignItems: "start !important" },
  ".justify-content-center": { justifyContent: "center" },
  ".justify-content-between": { justifyContent: "space-between" },
  ".text-center": { textAlign: "center" },
  ".text-start": { textAlign: "left" },
  ".text-end": { textAlign: "right" },
  ".text-justify": { textAlign: "justify" },
  ".ls-05": { letterSpacing: "-0.28px" },
  ".ls-1": { letterSpacing: "-0.75px" },
  ".lh-100": { lineHeight: "100%" },
  ".lh-150": { lineHeight: "150%" },
  ".small": { fontSize: "0.5rem" },
  ".smallest": { fontSize: "0.48rem" },
  ".row": {
    display: "flex",
    alignItems: "center",
    "&.three-checkboxes": {
      justifyContent: "space-around",
      minHeight: "6mm",
      maxHeight: "6mm",
      padding: "0.45mm 0"
    },
    "&.two-checkboxes": {
      justifyContent: "space-around",
      minHeight: "6mm",
      maxHeight: "6mm",
      padding: "0.45mm 0"
    }
  },
  ".col": { flex: "1 0 0%" },
  ".col-auto": { flex: "0 0 auto", width: "auto" },
  ".col-35": { maxWidth: "35mm", height: "9mm" },
  ".col-40": { maxWidth: "40mm", minWidth: "40mm", height: "9mm" },
  ".h-7": { minHeight: "7mm" },
  ".border-1": { border: "thin solid #000" },
  ".vh-100": {
    height: "inherit",
    minHeight: "100%",
    border: "thin solid red",
    display: "flex",
    flexDirection: "column",
    flex: 1
  },
  ".form-slot": {
    minHeight: "7mm",
    border: "thin solid black",
    borderRadius: "1mm",
    "&label": {
      fontSize: "9px",
      fontWeight: 500,
      letterSpacing: "-0.35px",
      marginLeft: "0.5mm"
    },
    "&.placa": { minHeight: "9mm" }
  },
   ".border-wrapper": {
    border: "thin solid black",
    borderRadius: "1mm",
    height: "100%"
  },
  ".red-tag": {
    maxHeight: "19mm",
    minHeight: "19mm",
    backgroundColor: "#ee1e32",
    padding: "2mm 0mm 2mm 2mm",
    fontSize: "11.5px",
    lineHeight: "140%",
    borderRadius: "1mm",
    "& > div:first-child": { letterSpacing: "-0.5px" },
  },
  ".blue-slots": {
    "&div": {
    borderRadius: "0.6mm",
    backgroundColor: "#13618d",
    marginTop: "0.3mm",
    padding: "1mm",
    color: "#fff",
    lineHeight: "96%",
    minHeight: "6.8mm",
    maxHeight: "6.8mm",
    display: "flex",
    alignItems: "center",
    letterSpacing: "-0.5px",
  },
  "&div.bg-secondary": { justifyContent: "center" },
  "&div .form-slot": {
    width: "100% !important",
    backgroundColor: "white",
    maxHeight: "5.4mm",
    height: "5.4mm",
    minHeight: "3.4mm",
    border: "none",
    marginBottom: "1px"
  },
  },
    ".icon-header": {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#13618d",
    color: "white",
    minHeight: "4mm",
    borderRadius: "0.6mm",
    "&span": {
      width: "100%",
      display: "block",
      padding: "1mm",
      borderRadius: "inherit"
      },
    "&.icon": {
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    marginLeft: "auto",
    padding: "1mm",
    minHeight: "inherit",
    borderRadius: "inherit"
  }
  },
  ".row.three-checkboxes": {
    justifyContent: "space-around",
    minHeight: "6mm",
    maxHeight: "6mm",
    padding: "0.45mm 0"
  },
  ".row.three-checkboxes, .row.two-checkboxes": {
    justifyContent: "space-around",
    minHeight: "6mm",
    maxHeight: "6mm",
    padding: "0.45mm 0"
  },
    
    
    
    
    
    
    

    
})